___
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-infra

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: cluster-infra

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: cluster-infra
