externalDns:
  args:
  - --source=ingress
  - --provider=aws
  - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
  - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
  - --registry=txt
  - --txt-owner-id=scos
  # - --domain-filter=${DNS_ZONE} # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones