apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "prometheus.grafana.fullname" . }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.grafana.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "prometheus.name" . }}
      component: "{{ .Values.grafana.name }}"
      release: {{ .Release.Name }}
  replicas: {{ .Values.grafana.replicaCount }}
  {{- if .Values.server.strategy }}
  strategy:
{{ toYaml .Values.server.strategy | indent 4 }}
  {{- end }}
  template:
    metadata:
    {{- if .Values.grafana.podAnnotations }}
      annotations:
{{ toYaml .Values.grafana.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: {{ template "prometheus.name" . }}
        component: "{{ .Values.grafana.name }}"
        release: {{ .Release.Name }}
    spec:
{{- if .Values.grafana.affinity }}
      affinity:
{{ toYaml .Values.grafana.affinity | indent 8 }}
{{- end }}
{{- if .Values.grafana.schedulerName }}
      schedulerName: "{{ .Values.grafana.schedulerName }}"
{{- end }}
      serviceAccountName: {{ template "prometheus.serviceAccountName.grafana" . }}
{{- if .Values.grafana.priorityClassName }}
      priorityClassName: "{{ .Values.grafana.priorityClassName }}"
{{- end }}
{{- if .Values.grafana.dashboards }}
      initContainers:
        - name: download-dashboards
          image: "{{ .Values.grafana.downloadDashboardsImage.repository }}:{{ .Values.grafana.downloadDashboardsImage.tag }}"
          imagePullPolicy: {{ .Values.grafana.downloadDashboardsImage.pullPolicy }}
          command: ["sh", "/etc/grafana/download_dashboards.sh"]
          volumeMounts:
            - name: config
              mountPath: "/etc/grafana/download_dashboards.sh"
              subPath: download_dashboards.sh
            - name: storage
              mountPath: "/var/lib/grafana"
              subPath: {{ .Values.grafana.persistentVolume.subPath }}
          {{- range .Values.grafana.extraSecretMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
{{- end }}
      {{- if .Values.grafana.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.grafana.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
{{- if .Values.grafana.sidecar.dashboards.enabled }}
        - name: {{ .Values.grafana.name }}-sc-dashboard
          image: "{{ .Values.grafana.sidecar.image }}"
          imagePullPolicy: {{ .Values.grafana.sidecar.imagePullPolicy }}
          env:
            - name: LABEL
              value: "{{ .Values.grafana.sidecar.dashboards.label }}"
            - name: FOLDER
              value: "{{ .Values.grafana.sidecar.dashboards.folder }}"
          resources:
{{ include "prometheus.resources" . | trim | indent 12 }}
          volumeMounts:
            - name: sc-dashboard-volume
              mountPath: {{ .Values.grafana.sidecar.dashboards.folder | quote }}
{{- end}}
{{- if .Values.grafana.sidecar.datasources.enabled }}
        - name: {{ .Values.grafana.name }}-sc-datasources
          image: "{{ .Values.grafana.sidecar.image }}"
          imagePullPolicy: {{ .Values.grafana.sidecar.imagePullPolicy }}
          env:
            - name: LABEL
              value: "{{ .Values.grafana.sidecar.datasources.label }}"
            - name: FOLDER
              value: "/etc/grafana/provisioning/datasources"
          resources:
{{ include "prometheus.resources" . | trim | indent 12 }}
          volumeMounts:
            - name: sc-datasources-volume
              mountPath: "/etc/grafana/provisioning/datasources"
{{- end}}
        - name: {{ .Values.grafana.name }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          resources:
{{ include "prometheus.resources" . | trim | indent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/etc/grafana/grafana.ini"
              subPath: grafana.ini
            - name: ldap
              mountPath: "/etc/grafana/ldap.toml"
              subPath: ldap.toml
{{- if .Values.grafana.dashboards }}
  {{- range $provider, $dashboards := .Values.grafana.dashboards }}
    {{- range $key, $value := $dashboards }}
      {{- if hasKey $value "json" }}
            - name: dashboards-{{ $provider }}
              mountPath: "/var/lib/grafana/dashboards/{{ $provider }}/{{ $key }}.json"
              subPath: "{{ $key }}.json"
      {{- end }}
    {{- end }}
  {{- end }}
{{- end -}}
{{- if .Values.grafana.dashboardsConfigMaps }}
  {{- range keys .Values.grafana.dashboardsConfigMaps }}
            - name: dashboards-{{ . }}
              mountPath: "/var/lib/grafana/dashboards/{{ . }}"
  {{- end }}
{{- end }}
{{- if .Values.grafana.datasources }}
            - name: config
              mountPath: "/etc/grafana/provisioning/datasources/datasources.yaml"
              subPath: datasources.yaml
{{- end }}
{{- if .Values.grafana.dashboardProviders }}
            - name: config
              mountPath: "/etc/grafana/provisioning/dashboards/dashboardproviders.yaml"
              subPath: dashboardproviders.yaml
{{- end }}
{{- if .Values.grafana.sidecar.dashboards.enabled }}
            - name: sc-dashboard-volume
              mountPath: {{ .Values.grafana.sidecar.dashboards.folder | quote }}
            - name: sc-dashboard-provider
              mountPath: "/etc/grafana/provisioning/dashboards/sc-dashboardproviders.yaml"
              subPath: provider.yaml
{{- end}}
{{- if .Values.grafana.sidecar.datasources.enabled }}
            - name: sc-datasources-volume
              mountPath: "/etc/grafana/provisioning/datasources"
{{- end}}
            - name: storage
              mountPath: "/var/lib/grafana"
              subPath: {{ .Values.grafana.persistentVolume.subPath }}
          {{- range .Values.grafana.extraSecretMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          ports:
            - name: service
              containerPort: {{ .Values.grafana.service.servicePort }}
              protocol: TCP
            - name: grafana
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "prometheus.grafana.fullname" . }}
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "prometheus.grafana.fullname" . }}
                  key: admin-password
            {{- if .Values.grafana.plugins }}
            - name: GF_INSTALL_PLUGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "prometheus.grafana.fullname" . }}
                  key: plugins
            {{- end }}
            {{- if .Values.smtp.existingSecret }}
            - name: GF_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.smtp.existingSecret }}
                  key: user
            - name: GF_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.smtp.existingSecret }}
                  key: password
            {{- end }}
{{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
{{- end }}
          {{- if .Values.grafana.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.grafana.envFromSecret }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
            failureThreshold: 10
            periodSeconds: 10
    {{- if .Values.grafana.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.grafana.nodeSelector | trim | indent 8 }}
    {{- end }}
    {{- if .Values.grafana.securityContext }}
      securityContext:
{{ toYaml .Values.grafana.securityContext | trim | indent 8 }}
    {{- end }}
    {{- if .Values.grafana.tolerations }}
      tolerations:
{{ toYaml .Values.grafana.tolerations | trim | indent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "prometheus.grafana.fullname" . }}
        {{- if .Values.grafana.dashboards }}
          {{- range keys .Values.grafana.dashboards }}
        - name: dashboards-{{ . }}
          configMap:
            name: {{ template "prometheus.grafana.fullname" $ }}-dashboards-{{ . }}
          {{- end }}
        {{- end }}
        {{- if .Values.grafana.dashboardsConfigMaps }}
          {{- range $provider, $name := .Values.grafana.dashboardsConfigMaps }}
        - name: dashboards-{{ $provider }}
          configMap:
            name: {{ $name }}
          {{- end }}
        {{- end }}
        - name: ldap
          secret:
            {{- if .Values.ldap.existingSecret }}
            secretName: {{ .Values.ldap.existingSecret }}
            {{- else }}
            secretName: {{ template "prometheus.grafana.fullname" . }}
            {{- end }}
            items:
              - key: ldap-toml
                path: ldap.toml
        - name: storage
      {{- if .Values.grafana.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.grafana.persistentVolume.existingClaim | default (include "prometheus.grafana.fullname" .) }}
      {{- else }}
          emptyDir: {}
      {{- end -}}
      {{- if .Values.grafana.sidecar.dashboards.enabled }}
        - name: sc-dashboard-volume
          emptyDir: {}
        - name: sc-dashboard-provider
          configMap:
            name: {{ template "prometheus.grafana.fullname" . }}-config-dashboards
      {{- end }}
      {{- if .Values.grafana.sidecar.datasources.enabled }}
        - name: sc-datasources-volume
          emptyDir: {}
      {{- end -}}
      {{- range .Values.grafana.extraSecretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
      {{- end }}
